linters:
  auto-fix: false
  enable:
    - deadcode
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - ineffassign
    - lll
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - varcheck
run:
  skip-dirs:
    - hack
    - dist
    - keps
    - kind-*

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  lll:
    line-length: 250
  dupl:
    threshold: 400
  goimports:
    # Don't use 'github.com/kudobuilder/kuttl', it'll result in unreliable output!
    local-prefixes: github.com/kudobuilder
issues:
  # ignore errchecks for test files
  exclude-rules:
  - path: _test\.go
    linters:
    - errcheck
