linters:
  auto-fix: false
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - decorder
    - dogsled
    - durationcheck
    - dupl
    - errcheck
    - errname
    - exportloopref
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - nosprintfhostport
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
run:
  go: '1.17'
  skip-dirs:
    - hack
    - dist
    - keps
    - kind-*

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  lll:
    line-length: 250
  dupl:
    threshold: 400
  goimports:
    # Don't use 'github.com/kyverno/kuttl', it'll result in unreliable output!
    local-prefixes: github.com/kyverno
issues:
  # ignore errchecks for test files
  exclude-rules:
  - path: _test\.go
    linters:
    - errcheck
