version: "2"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - ineffassign
    - interfacebloat
    - lll
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - nilnesserr
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    # - wsl_v5  # temporarily disabled - has 41 issues
    - zerologlint
  disable:
  # These linters are disabled ONLY because fixing/investigating their complaints initially was too overwhelming.
  # We SHOULD try and evaluate each of them eventually and either fix their reports
  # or comment here on why we decided to not listen to them.
    - cyclop
    - depguard
    - err113
    - errorlint
    - exhaustruct
    - forbidigo
    - funlen
    - gocognit
    - godot
    - godox
    - gosec
    - inamedparam
    - intrange
    - ireturn
    - gochecknoglobals
    - maintidx
    - mnd
    - musttag
    - nestif
    - nilnil
    - nlreturn
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - tagalign
    - testifylint
    - testpackage
    - thelper
    - varnamelen
    - wrapcheck
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    lll:
      line-length: 250
    dupl:
      threshold: 400
    govet:
      settings:
        printf:
          funcs:
            - (github.com/kudobuilder/kuttl/internal/utils.Logger).Logf
            - (github.com/kudobuilder/kuttl/internal/utils.TestLogger).Logf
            - (github.com/kudobuilder/kuttl/internal/case.clientWithKubeConfig).Logf
            - (github.com/kudobuilder/kuttl/internal/case.clientWithKubeConfig).Wrapf
    # TODO: fix the `context` usage in step package and enable these linters.
    usetesting:
      context-background: false
      context-todo: false
  exclusions:
    paths:
      - hack
      - dist
      - keps
      - kind-*

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      # Don't use 'github.com/kudobuilder/kuttl', it'll result in unreliable output!
      local-prefixes:
      - github.com/kudobuilder

