linters:
  auto-fix: false
  enable:
    - asasalint
    - bodyclose
    - containedctx
    - dogsled
    - dupl
    - errcheck
    - errname
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - grouper
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace
run:
  go: '1.17'
  skip-dirs:
    - hack
    - dist
    - keps
    - kind-*

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  lll:
    line-length: 250
  dupl:
    threshold: 400
  goimports:
    # Don't use 'github.com/kudobuilder/kuttl', it'll result in unreliable output!
    local-prefixes: github.com/kudobuilder
issues:
  # ignore errchecks for test files
  exclude-rules:
  - path: _test\.go
    linters:
    - errcheck
