# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  e2e-test:
    machine: true
    steps:
      - checkout
      - run: echo 'export INTEGRATION_OUTPUT_JUNIT="true"' >> $BASH_ENV
      - run: ./test/run_tests.sh e2e-test
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: kind-logs.tar.bz2

workflows:
  version: 2
  e2e-test:
    jobs:
      - e2e-test
