apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testasserts.kuttl.dev
spec:
  group: kuttl.dev
  names:
    kind: TestAssert
    plural: testasserts
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true # served as to allow IDEs to remotely load them and offer coding assistance
      storage: true
      schema:
        openAPIV3Schema: #! inlined from teststep-json-schema.yaml where authoring is made easier. See https://github.com/crossplane/crossplane/issues/3197#issuecomment-1191479570 for details
          description: The TestAssert object can be used to specify settings for a test step's assert and must be specified in the test step's assert YAML.
          type: object
          properties:
            timeout:
              description: Number of seconds that the test is allowed to run for
              type: integer
              default: 30
