name: DCO
on: [pull_request]

jobs:
  commits_check_job:
    runs-on: ubuntu-latest
    name: DCO check
    steps:
    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@v1.3.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: DCO Check
      uses: tim-actions/dco@v1.1.0
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}
