name: "End-to-end tests"

on:
  push:
    branches:
      - main
      - releases/*
  pull_request:
    branches:
      - main
      - releases/*

jobs:
  e2e-tests:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: "Run end-to-end tests"
      run: make e2e-test TEST_FLAGS=-v
