name: "E2E tests"

on:
  push:
    branches:
      - main
      - releases/*
  pull_request:
    branches:
      - main
      - releases/*

jobs:
  e2e-tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-go@v2.1.4
      with:
        go-version: 1.18
    - uses: actions/checkout@v2.4.0
    - name: "Run E2E tests"
      run: make e2e-test INTEGRATION_OUTPUT_JUNIT="true"
