name: "Integration tests"

on:
  push:
    branches:
      - main
      - releases/*
  pull_request:
    branches:
      - main
      - releases/*

jobs:
  integration-tests:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-go@v7
      with:
        go-version-file: go.mod
    - name: "Run integration tests"
      run: make integration-test INTEGRATION_OUTPUT_JUNIT="true" TEST_FLAGS="-v -race"
