name: "Lint code"

on:
  push:
    branches:
      - main
      - releases/*
  pull_request:
    branches:
      - main
      - releases/*

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: "Lint the code"
      run: make lint
    - name: "Verify generate"
      run: ./hack/verify-generate.sh
    - name: "Verify go clean"
      run: ./hack/verify-go-clean.sh
