name: "Unit tests"

on:
  push:
    branches:
      - main
      - releases/*
  pull_request:
    branches:
      - main
      - releases/*

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-go@v7
      with:
        go-version-file: go.mod
    - name: "Run unit tests"
      run: make test TEST_FLAGS="-v -race"
